# Copyright 2026 INNO LOTUS PTY LTD
# SPDX-License-Identifier: Apache-2.0

"""NWP error code wire constants — mirror of `spec/error-codes.md` NWP section."""

from __future__ import annotations

# ── Auth ─────────────────────────────────────────────────────────────────────
AUTH_NID_SCOPE_VIOLATION    = "NWP-AUTH-NID-SCOPE-VIOLATION"
AUTH_NID_EXPIRED            = "NWP-AUTH-NID-EXPIRED"
AUTH_NID_REVOKED            = "NWP-AUTH-NID-REVOKED"
AUTH_NID_UNTRUSTED_ISSUER   = "NWP-AUTH-NID-UNTRUSTED-ISSUER"
AUTH_NID_CAPABILITY_MISSING = "NWP-AUTH-NID-CAPABILITY-MISSING"
AUTH_ASSURANCE_TOO_LOW      = "NWP-AUTH-ASSURANCE-TOO-LOW"
AUTH_REPUTATION_BLOCKED     = "NWP-AUTH-REPUTATION-BLOCKED"

# ── Query ─────────────────────────────────────────────────────────────────────
QUERY_FILTER_INVALID        = "NWP-QUERY-FILTER-INVALID"
QUERY_FIELD_UNKNOWN         = "NWP-QUERY-FIELD-UNKNOWN"
QUERY_CURSOR_INVALID        = "NWP-QUERY-CURSOR-INVALID"
QUERY_REGEX_UNSAFE          = "NWP-QUERY-REGEX-UNSAFE"
QUERY_VECTOR_UNSUPPORTED    = "NWP-QUERY-VECTOR-UNSUPPORTED"
QUERY_AGGREGATE_UNSUPPORTED = "NWP-QUERY-AGGREGATE-UNSUPPORTED"
QUERY_AGGREGATE_INVALID     = "NWP-QUERY-AGGREGATE-INVALID"
QUERY_STREAM_UNSUPPORTED    = "NWP-QUERY-STREAM-UNSUPPORTED"

# ── Action ────────────────────────────────────────────────────────────────────
ACTION_NOT_FOUND             = "NWP-ACTION-NOT-FOUND"
ACTION_PARAMS_INVALID        = "NWP-ACTION-PARAMS-INVALID"
ACTION_IDEMPOTENCY_CONFLICT  = "NWP-ACTION-IDEMPOTENCY-CONFLICT"

# ── Task ──────────────────────────────────────────────────────────────────────
TASK_NOT_FOUND          = "NWP-TASK-NOT-FOUND"
TASK_ALREADY_CANCELLED  = "NWP-TASK-ALREADY-CANCELLED"
TASK_ALREADY_COMPLETED  = "NWP-TASK-ALREADY-COMPLETED"
TASK_ALREADY_FAILED     = "NWP-TASK-ALREADY-FAILED"

# ── Subscribe ─────────────────────────────────────────────────────────────────
SUBSCRIBE_STREAM_NOT_FOUND  = "NWP-SUBSCRIBE-STREAM-NOT-FOUND"
SUBSCRIBE_LIMIT_EXCEEDED    = "NWP-SUBSCRIBE-LIMIT-EXCEEDED"
SUBSCRIBE_FILTER_UNSUPPORTED = "NWP-SUBSCRIBE-FILTER-UNSUPPORTED"
SUBSCRIBE_INTERRUPTED       = "NWP-SUBSCRIBE-INTERRUPTED"
SUBSCRIBE_SEQ_TOO_OLD       = "NWP-SUBSCRIBE-SEQ-TOO-OLD"

# ── Infrastructure ────────────────────────────────────────────────────────────
BUDGET_EXCEEDED          = "NWP-BUDGET-EXCEEDED"
DEPTH_EXCEEDED           = "NWP-DEPTH-EXCEEDED"
GRAPH_CYCLE              = "NWP-GRAPH-CYCLE"
NODE_UNAVAILABLE         = "NWP-NODE-UNAVAILABLE"
RATE_LIMIT_EXCEEDED      = "NWP-RATE-LIMIT-EXCEEDED"

# ── Manifest ──────────────────────────────────────────────────────────────────
MANIFEST_VERSION_UNSUPPORTED = "NWP-MANIFEST-VERSION-UNSUPPORTED"
MANIFEST_NODE_TYPE_REMOVED   = "NWP-MANIFEST-NODE-TYPE-REMOVED"
MANIFEST_NODE_TYPE_UNKNOWN   = "NWP-MANIFEST-NODE-TYPE-UNKNOWN"

# ── Topology (alpha.4+) ───────────────────────────────────────────────────────
TOPOLOGY_UNAUTHORIZED       = "NWP-TOPOLOGY-UNAUTHORIZED"
TOPOLOGY_UNSUPPORTED_SCOPE  = "NWP-TOPOLOGY-UNSUPPORTED-SCOPE"
TOPOLOGY_DEPTH_UNSUPPORTED  = "NWP-TOPOLOGY-DEPTH-UNSUPPORTED"
TOPOLOGY_FILTER_UNSUPPORTED = "NWP-TOPOLOGY-FILTER-UNSUPPORTED"

# ── Reserved type (alpha.5+) ─────────────────────────────────────────────────
RESERVED_TYPE_UNSUPPORTED = "NWP-RESERVED-TYPE-UNSUPPORTED"
